# Generated by Django 5.2 on 2025-04-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notes_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='note',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
