# Generated by Django 5.2 on 2025-04-23 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
