# Generated by Django 5.2 on 2025-04-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0003_rename_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
