# Generated by Django 5.2 on 2025-04-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
