# Generated by Django 5.2 on 2025-04-23 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0005_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
