# Generated by Django 5.2 on 2025-04-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0006_summary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='note_management.note'),
        ),
    ]
