# Generated by Django 5.2 on 2025-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0007_alter_summary_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='graph',
            field=models.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='summary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
