# Generated by Django 5.2 on 2025-04-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0008_bookmark'),
        ('note_management', '0008_summary_graph_summary_updated_at'),
    ]

    operations = [
    ]
