# Generated by Django 5.2 on 2025-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_management', '0009_merge_20250425_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='graph',
            field=models.JSONField(default=dict),
        ),
    ]
